import os
from dotenv import load_dotenv

load_dotenv()

PORT = os.getenv("PORT")
HOST = os.getenv("HOST")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME")

CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
CLAUDE_MODEL_NAME = os.getenv("CLAUDE_MODEL_NAME")
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai")

AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID")
AIRTABLE_TABLE_KTP = os.getenv("AIRTABLE_TABLE_KTP")
AIRTABLE_TABLE_NPWP = os.getenv("AIRTABLE_TABLE_NPWP")
AIRTABLE_TABLE_KK = os.getenv("AIRTABLE_TABLE_KK")
AIRTABLE_TABLE_BPKB_PEMILIK = os.getenv("AIRTABLE_TABLE_BPKB_PEMILIK")
AIRTABLE_TABLE_BPKB_KENDARAAN = os.getenv("AIRTABLE_TABLE_BPKB_KENDARAAN")
AIRTABLE_TABLE_STNK = os.getenv("AIRTABLE_TABLE_STNK")
