import os

PORT = os.environ.get("PORT")
HOST = os.environ.get("HOST")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
OPENAI_MODEL_NAME = os.environ.get("OPENAI_MODEL_NAME")

CLAUDE_API_KEY = os.environ.get("CLAUDE_API_KEY")
CLAUDE_MODEL_NAME = os.environ.get("CLAUDE_MODEL_NAME")
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "openai")

AIRTABLE_API_KEY = os.environ.get("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.environ.get("AIRTABLE_BASE_ID")
AIRTABLE_TABLE_KTP = os.environ.get("AIRTABLE_TABLE_KTP")
AIRTABLE_TABLE_NPWP = os.environ.get("AIRTABLE_TABLE_NPWP")
AIRTABLE_TABLE_KK = os.environ.get("AIRTABLE_TABLE_KK")
AIRTABLE_TABLE_BPKB_PEMILIK = os.environ.get("AIRTABLE_TABLE_BPKB_PEMILIK")
AIRTABLE_TABLE_BPKB_KENDARAAN = os.environ.get("AIRTABLE_TABLE_BPKB_KENDARAAN")
AIRTABLE_TABLE_STNK = os.environ.get("AIRTABLE_TABLE_STNK")
